# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: On Push to Master

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Gradle
        run: gradle build

      - name: Publish to Maven Central
        run: gradle publish
        env:
          ossrhUsername: ${{ secrets.ossrhUsername }}
          ossrhPassword: ${{ secrets.ossrhPassword }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.ORG_GRADLE_PROJECT_signingKey }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.ORG_GRADLE_PROJECT_signingPassword }}

      - name: Close and Release from Staging if not Snapshot
        run: ./scripts/closeAndReleaseIfNotSnapshot.sh
        env:
          ossrhUsername: ${{ secrets.ossrhUsername }}
          ossrhPassword: ${{ secrets.ossrhPassword }}
